---
title: "TBM"
author: "Mostafa Kamal"
date: "`r Sys.Date()`"
output: html_document
---


### loading the data



```{r}

library(readxl)
library(plm)
library(tidyverse)



```

```{r}

# loading the data
data <- read_excel("Data for analysis.xlsx", sheet = "Final")
data <- na.omit(data)



```


```{r}

# summary statistics for the banks (here we need to put all the values from different)

leverdUnleverd <- data %>% 
  group_by(`Bank Name`) %>% 
  summarise(
    N = n(),
    Min = min(`Assets/Equity`),
    Mean = mean(`Assets/Equity`),
    q1 = quantile(`Assets/Equity`,probs = 0.25),
    Median = median(`Assets/Equity`),
    q3 = quantile(`Assets/Equity`,probs = 0.75),
    Max = max(`Assets/Equity`)
    
  )

leverdUnleverd

```




```{r}
# 1st and 4th quantile of the overall asset/equity
  
data %>% 
  summarise(
    quantile = quantile(`Assets/Equity`, probs = c(0.25,0.75))
  )

# finding the levered and unlevered firms

leverdUnleverd %>% 
  filter(q1<=10.7 | q1>=21.3) %>% 
  arrange(q1)


# partioning the data in the highly levered and lower levered dataset

dataPart <- data %>% 
  # select(`Bank Name`, Year, LL, HL) %>% 
  mutate(
    LL = case_when(
    `Bank Name`== "Truist Financial"~1,
    `Bank Name`== "M&T Bank"~1,
    `Bank Name`== "PNC"~1,
    `Bank Name`== "Fifth Third Bancorp"~1,
    `Bank Name`== "Bank of New York Mellon"~1,
    `Bank Name`== "Bank of America"~1,
    `Bank Name`== "US Bancorp"~1,
    `Bank Name`== "JPMorgan Chase"~1,
    TRUE ~ 0),
    HL = case_when(
      `Bank Name`== "Deutsche Bank"~1,
      TRUE ~ 0)) 

dataPart %>% 
  # group_by(LL,HL) %>% 
  filter(HL==1 | LL==1) %>%
  group_by(LL,HL) %>%
  summarise(
    obs=n(),
    assets=mean(`Total Assets`/1000),
    costOfDebtFinancing = mean(`Interest Expense%`),
    growthRateOfDebtFinancing =mean(`Equity Growth`),
    growthRateOfLending = mean(`Loan Growth`),
    assetRisk = sd(`Total Assets`),
    ROA = mean(`Return on Assets`)
    
    
  ) %>% t()

```

```{r}

# Need to draw the figures (4 figures)

library(ggplot2)

# Asset and total equity (i)

data %>% 
  group_by(Year) %>% 
  summarise(
    meanAE=median(`Assets/Equity`),
    q1 = quantile(`Assets/Equity`, probs = 0.25),
    q3 = quantile(`Assets/Equity`, probs = 0.75)
  ) %>% 
  ungroup() %>% 
  pivot_longer(cols = -Year,names_to = "variable",values_to = "value") %>% 
  ggplot(mapping = aes(x=Year, y= value, col =variable))+
  geom_line(size =1.2)+
  ylim(c(8,30))+
  theme_minimal()

# RWA and Tier 1 capital ratio (iii)

data %>% 
  group_by(Year) %>% 
  summarise(
    meanAE=median(`RWA/Tier 1`),
    q1 = quantile(`RWA/Tier 1`, probs = 0.25),
    q3 = quantile(`RWA/Tier 1`, probs = 0.75)
  ) %>% 
  ungroup() %>% 
  pivot_longer(cols = -Year,names_to = "variable",values_to = "value") %>% 
  ggplot(mapping = aes(x=Year, y= value, col =variable))+
  geom_line(size =1.2)+
  # ylim(c(8,30))+
  theme_minimal()
  

# Total fair value of the asset and the market value of the equity (need the market value of equity) (iv)

data %>% 
  group_by(Year) %>% 
  summarise(
    meanAE=median(`Total Fair Value Assets/Total Equity`),
    q1 = quantile(`Total Fair Value Assets/Total Equity`, probs = 0.25),
    q3 = quantile(`Total Fair Value Assets/Total Equity`, probs = 0.75)
  ) %>% 
  ungroup() %>% 
  pivot_longer(cols = -Year,names_to = "variable",values_to = "value") %>% 
  ggplot(mapping = aes(x=Year, y= value, col =variable))+
  geom_line(size =1.2)+
  # ylim(c(8,30))+
  theme_minimal()

```

